name: Greg Boulden
favicon: null
layout_spectrum: 0.87909
typography_spectrum: 0.9303
title: Creative at Play.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 0.8957992445211858
  saturation: 0.9345818592701107
  rhythmicContrast: 0.6530849465634674
purpose: []
